name: Build and Publish

on:
  push:
    tags: ["v*"]
  workflow_dispatch:

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    permissions:
      id-token: write # 👈 required for OIDC
      contents: read # needed for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: lintai/ui/frontend/yarn.lock

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install frontend dependencies
        run: |
          cd lintai/ui/frontend
          yarn install --frozen-lockfile

      - name: Build frontend
        run: python scripts/build-frontend.py

      - name: Clean dist directory
        run: rm -rf dist

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install build

      - name: Build Python package
        run: python -m build

      - name: Publish to PyPI via OIDC
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          verbose: true
